@startuml CVRP_Component_Class_Diagram

title CVRP Component Class Diagram

skinparam nodesep 10
skinparam ranksep 30
top to bottom direction

namespace SI::CVRP {

class TNode {
  + TNodeID ID
  + TCapacity Demand
  + TNode(TNodeID, TCapacity)
  + TNode(pb::Customer, int64_t)
  + operator==(TNode)
  + operator!=(TNode)
  + operator<(TNode)
  + CreateDummy(int64_t)
}

class TNodeWithCoordinate {
  + base::Coordinate Coordinate
  + int64_t UIDFromFrontend
  + TNodeWithCoordinate(TNode, base::Coordinate)
}

class TNodesWithCoordinates {
  + std::vector<TNodeWithCoordinate> Nodes
  + TNodesWithCoordinates(std::vector<TNode>)
  + TNodesWithCoordinates(pb::Request)
}

class TProblem {
  - TNode Depot
  - std::vector<TNode> Customers
  - TDistanceTable DistanceMatrix
  + TProblem(TNodesWithCoordinates, TDistanceTable)
  + Distance(TNode, TNode)
}

class TSolution {
  - TProblem Problem
  - TRoutes Routes
  - TDistance TotalDistance
  + TSolution(TProblem, TRoutes, TDistance)
  + RouteWithCoordinates(TRoute)
  + operator<(TSolution)
}

class TRouteIterator {
  + TRouteIterator()
  + TRouteIterator(TSolution, TRoute)
  + operator++()
  + TNodeWithCoordinate operator*()
  + operator==(TRouteIterator)
  + operator!=(TRouteIterator)
}

class TFileInstanceReader {
  + TFileInstanceReader(std::string)
  + ~TFileInstanceReader()
  + Read()
  - ReadBaseInfo(std::string)
  - ReadNodes(std::string)
  - ReadDemands(std::string)
  - ReadDepot(std::string)
  - CalcDistanceTable()
  - CalcDistance(Coord, Coord)
}

class TRoute << (T,#FF7700) >> {
    ..std::vector<TNode>..
}

TNode <|-- TNodeWithCoordinate: extends
TNodesWithCoordinates o-- TNodeWithCoordinate
TProblem o-- TNodesWithCoordinates
TProblem -down-o TSolution
TSolution o-- TRouteIterator: provides
TRouteIterator o-- TRoute
TSolution  o-- TRoute
TFileInstanceReader --> TProblem

}

@enduml