@startuml PSO_Component_Class_Diagram

title PSO Component Class Diagram

skinparam nodesep 50
skinparam ranksep 80
' set separator none
skinparam linetype ortho



namespace SI::PSO {

class TParticle {
  + TParticle(CVRP::TProblem)
  + TParticle(CVRP::TProblem, TCoordinates)
  + TotalDistance()
  + GetRoutes()
  + Evaluate()
  + BestDistance()
  + BestPosition()
  + Update(TParameters, TDistance)
  + MakeTwoOpt()
  {static} MakeTwoOpt(CVRP::TProblem, TCoordinates)
  - CVRP::TProblem Problem_
  - CVRP::TRoutes Routes
  - TCoordinates Position
  - TCoordinates Velocity
  - TCoordinates BestPosition
  - TDistance BestDistance
}

class TSolver {
  + TSolver(CVRP::TProblem, TParameters)
  + CVRP::TSolution Solve()
  + GetBestDistance()
  - ConstructBestRoutes()
  - CVRP::TProblem Problem
  - TParameters Parameters
  - vector<TParticle> Particles
  - TCoordinates BestPosition
  - TDistance BestDistance
}

class TParameters {
  + SwarmSize  = 25
  + MaxIterations = 10000
  + W = 0.6
  + C1 = 1.5
  + C2 = 1.5
}

class TCoordinates<< (T,#FF7700) >> {
  ..std::vector<int32_t>..
}

TSolver "1" *-- "1" TParameters : uses >
TSolver "1" *-- "1..*" TParticle : manages >
TParticle "1" *-- "1" TCoordinates : maintains >


}